from langchain_huggingface import HuggingFaceEndpoint, ChatHuggingFace
from dotenv import load_dotenv

#Annotated can be used to attach some more info with the type
#Optional allows to skip some thing if not present
#Literal helps to provide options to choose from, and give the output on those options

load_dotenv()

llm = HuggingFaceEndpoint(
    repo_id="openai/gpt-oss-120b",
    task="text-generation"
)

model = ChatHuggingFace(llm=llm)

json_schema = {
    "title": "Review",  #title field is important
  "type": "object",
  "properties": {
    "summary": {
      "type": "string",
      "description": "Write summary for the review"
    },
    "sentiment": {
      "type": "string",
      "enum": ["pos", "neg", "neu"],
      "description": "Give sentiment as positive, negative or neutral"
    },
    "pros": {
      "type": ["array", "null"],
      "items": {
        "type": "string"
      },
      "description": "Write down all the pros inside a list"
    },
    "cons": {
      "type": ["array", "null"],
      "items": {
        "type": "string"
      },
      "description": "Write down all the cons inside a list"
    }
  },
  "required": [
    "summary",
    "sentiment"
  ]
}

#what happens in backend when with_structured_output is called is a prompt is generated by default and passed to the llm on how to show the result in JSON format
structured_model = model.with_structured_output(json_schema)

result = structured_model.invoke("The hardware is damaged and is frustating") #return pydantic object

print(result)  #return dict
print(result['summary'])
print(result['sentiment'])
print(result['pros']) #cant have default values, returns empty list