from langchain_huggingface import HuggingFaceEndpoint, ChatHuggingFace
from dotenv import load_dotenv
from typing import TypedDict, Annotated, Optional, Literal

#Annotated can be used to attach some more info with the type
#Optional allows to skip some thing if not present
#Literal helps to provide options to choose from, and give the output on those options

load_dotenv()

llm = HuggingFaceEndpoint(
    repo_id="openai/gpt-oss-120b",
    task="text-generation"
)

model = ChatHuggingFace(llm=llm)

#schema
class Review(TypedDict):
    summary: Annotated[str, "Write summary for the review"]
    sentiment: Annotated[Literal['pos','neg','neu'], "Give sentiment as positive, negative or neutral"]
    pros: Annotated[list[str], "Write down all the pros inside a list"]
    cons: Annotated[Optional[list[str]], "Write down all the cons of the review"]

#what happens in backend when with_structured_output is called is a prompt is generated by default and passed to the llm on how to show the result in JSON format
structured_model = model.with_structured_output(Review)

result = structured_model.invoke("The hardware is damaged and is frustating")

print(result)
print(result['summary'])
print(result['sentiment'])
print(result['pros']) #empty as optional and no pros in review